name: Notes CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run docs:build
    - run: npm test
      env:
        CI: true
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
          FTP_SERVER: mintnoii.com
          FTP_USERNAME: mintnoii
          FTP_PASSWORD: ${{ secrets.FTPPWD }}
          LOCAL_DIR: docs/.vuepress/dist
          REMOTE_DIR: /root/W-Qing/Notes/
          ARGS: --delete --transfer-all --exclude=logreport --verbose
