name: W-Qing's Notes

# 设置监听仓库事件
on:
   # 监听master分支的推送
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.NotesDeploy }}
        BRANCH: master
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run build
